[pytest]
#test discovery
testpaths=tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*

#Addopts
addopts=
    -v
    --strict-markers
    --tb=short
    --html=output/reports/test_report.html
    # info warn debug error
    --log-level=INFO

markers=
    smoke:Smoke tests
    regression:Regression tests
    login:login related tests
    dashboard:Dashboard tests

#logging
log_cli=true
log_cli_level=INFO
log_cli_format=%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
