class UserApiObjects:
    baseurl="https://automationexercise.com/"
    path_param="api"
    productsList="/productsList"
    brandsList="/brandsList"
    SEARCH_PRODUCT="/searchProduct"
    create_account="/createAccount"
    GET_USER_BY_EMAIL="/getUserDetailByEmail"
    UPDATE_USER_DETAIL="/updateAccount"
    DELETE_ACCOUNT="/deleteAccount"
    VERIFY_LOGIN="/verifyLogin"
